importdata('task3.m'); 
importdata('task1.m'); 
yesnew = filter(num,den,yes); 
nonew = filter(num,den,no);   
yesshort = yes(Fs*0.35:Fs*0.40); 
yesnewshort = yesnew(Fs*0.35:Fs*0.40); 
tshort = 0.35:1/Fs:0.40; 
figure(1);
plot(tshort,yesshort);
title('50ms Short Segment Before Filtering'); 
xlabel('Time In Seconds');ylabel('Magnitude'); 
figure(2);
plot(tshort,yesnewshort); 
title('50ms Short Segment After Filtering'); 
xlabel('Time In Seconds');ylabel('Magnitude');  
difference = abs(yesnewshort-yesshort); 
figure(3);
plot(tshort,difference);
title('Difference Between The Two Waveforms'); 
xlabel('Time In Seconds');ylabel('Magnitude'); 