a=importdata('task1.m');  
sound(no); 
sound(no1); 
sound(no2);
Fs = 8000; 
max_value = max(abs(no2));  
no2 = no2/max_value; 
no2 = no2(Fs*0.25:Fs*0.30);    
sound(no2); 
ext = 0.25:1/Fs:0.30;  
figure(1); 
plot(ext,no2); 
title('50ms Segment of ‘o’ in no Which is roughly Periodic');
xlabel('Time In Seconds -------->'); ylabel('Magnitude----->');
dtftno1 = abs(fft(no2));  
dtftno1 = dtftno1(1:ceil((length(dtftno1)/2))); 
tt = linspace(1/Fs,Fs/2,length(dtftno1)); 
figure(2);
plot(tt,dtftno1); 
title('Linear Magnitude Spectrum Of ‘o’ Segment'); 
grid on; 
xlabel('Frequency In Hz'); ylabel('Magnitude'); 
dtftno1log=20*log10(dtftno1); 
figure(3);
plot(tt,dtftno1log); 
title('Log Magnitude Spectrum Of ‘o’ Segmnet (dB Scale)'); 
xlabel('Frequency In Hz'); ylabel('Magnitude'); 
grid on;    