 r = audiorecorder(8000,16,1); 
disp('Start speaking.') 
recordblocking(r,1); 
disp('End of Recording.'); 
play(r); 
yes = getaudiodata(r);  
g = audiorecorder(8000,16,1); 
disp('Start speaking.') 
recordblocking(g,1); 
disp('End of Recording.'); 
play(g); 
no = getaudiodata(g);  
yes1 = yes(1:4000); 
yes2 = yes(4001:8000);  
no1 = no(1:4000); 
no2 = no(4001:8000);  
figure(1); 
plot(yes); 
title('Yes Speech Signal (8000Samples/sec)'); 
xlabel('Samples---->');ylabel('Magnitude');  
figure(2); 
plot(yes1); 
title('One Vector Of 4000 Samples (half second) Of Yes'); 
xlabel('Samples----->');ylabel('Magnitude');  
figure(3); 
plot(yes2); 
title('Second Vector Of 4000 Samples (half second) Of Yes'); 
xlabel('Samples----->');ylabel('Magnitude'); 
n = size(yes); 
Fs = 8000; 
ts = 1/Fs; 
tmax = (n-1)*ts; 
t = 0:ts:tmax; 
figure(4); 
plot(t,yes); 
title('Yes Speech Signal (8000Samples/sec)'); 
xlabel('Time In Seconds----->');ylabel('Magnitude');  
ts1 = 1/Fs; 
tmax1 = ((n/2)-1)*ts1; 
t1 = 0:ts1:tmax1; 
figure(5); 
plot(t1,yes1);
title('One Vector Of 4000 Samples (half second) Of Yes'); 
xlabel('Time In Seconds----->');ylabel('Magnitude');  
ts2 = 1/Fs; 
tmax2 = ((n/2)-1)*ts2; 
t2 = 0:ts2:tmax2; 
figure(6); 
plot(t2,yes2);
title('Second Vector Of 4000 Samples (half second) Of Yes'); 
xlabel('Time In Seconds----->');ylabel('Magnitude');  
figure(7); 
plot(no); 
title('No Speech Signal (8000Samples/sec)'); 
xlabel('Samples---->');ylabel('Magnitude');  
figure(8); 
plot(no1); 
title('One Vector Of 4000 Samples (half second) Of No'); 
xlabel('Samples----->');ylabel('Magnitude');  
figure(9); 
plot(no2); 
title('Second Vector Of 4000 Samples (half second) Of No'); 
xlabel('Samples----->');ylabel('Magnitude');  
n = size(no); 
Fs = 8000; 
ts = 1/Fs; 
tmax = (n-1)*ts; 
t = 0:ts:tmax; 
figure(10);
plot(t,no); 
title('No Speech Signal (8000Samples/sec)'); 
xlabel('Time In Seconds----->');ylabel('Magnitude');  
ts1 = 1/Fs; 
tmax1 = ((n/2)-1)*ts1; 
t1 = 0:ts1:tmax1; 
figure(11); 
plot(t1,no1);
title('One Vector Of 4000 Samples (half second) Of No');
xlabel('Time In Seconds----->');ylabel('Magnitude');  
ts2 = 1/Fs; 
tmax2 = ((n/2)-1)*ts2; 
t2 = 0:ts2:tmax2; 
figure(12); 
plot(t2,no2);
title('Second Vector Of 4000 Samples (half second) Of No'); 
xlabel('Time In Seconds----->');ylabel('Magnitude'); 